function [fitresult, gof] = createFit2(depth_NGRIP, GICC05_age)
%CREATEFIT2(DEPTH_NGRIP,GICC05_AGE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : depth_NGRIP
%      Y Output: GICC05_age
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Apr-2018 18:36:04


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( depth_NGRIP, GICC05_age );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'GICC05_age vs. depth_NGRIP', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel depth_NGRIP
ylabel GICC05_age
grid on
end

