function [fitresult, gof] = createFit1(momentum, lambda_d1, w_lambda1)
%CREATEFIT1(MOMENTUM,LAMBDA_D1,W_LAMBDA1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : momentum
%      Y Output: lambda_d1
%      Weights : w_lambda1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Dec-2017 12:07:21


%% Fit: 'untitled fit 1'.
[xData, yData, weights] = prepareCurveData( momentum, lambda_d1, w_lambda1 );

% Set up fittype and options.
ft = fittype( 'a/x', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.306478539482128;
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
errorbar(xData,yData,e_lambda1)
hold on
h = plot( fitresult, xData, yData );
legend( h, 'Data', 'y = 3.722e-24/x', 'Location', 'NorthEast' );
% Label axes
xlabel('momentum [kg*m/s]')
ylabel \lambda/d_1

grid on
hold off

